---
- name: Pull sentry self-hosted github
  git:
    repo: https://github.com/getsentry/self-hosted.git
    dest: /srv/sentry/
    version: master

- name: Updating Sentry
  command:
    chdir: /srv/sentry/
    cmd: ./install.sh

- name: docker-compuse up -d
  command:
    chdir: /srv/sentry/
    cmd: docker-compose up -d

- name: Register sentry in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/sentry.json
  notify:
    - reload consul
  when: disable_consul_services_ie_staging is not defined

